---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/mhzen/biru
name: biru
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: dnf
    repos:
      files:
        - https://download.opensuse.org/repositories/home:manuelschneid3r/Fedora_%OS_VERSION%/home:manuelschneid3r.repo
      copr:
        - alternateved/keyd
        - monkeygold/nautilus-open-any-terminal
      cleanup: true
    install:
      packages:
        - keyd
        - albert
        - fish
        - nautilus-open-any-terminal
        - podman-docker

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: justfiles
    include:
      - biru.just

  - type: brew
    brew-analytics: false

  # - type: script
  #   snippets:
  #     - "mkdir /nix" # https://github.com/DeterminateSystems/nix-installer/issues/1445

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

